export default {
    //JOIN_CAR:"JOIN_CAR" 例如
    GET: "GET",
    UPRECOMMENDLIST: "UPRECOMMENDLIST",
    UPPERFORMANCEDETAIL: "UPPERFORMANCEDETAIL",
    GET_FLOOR_SHOW: "GET_FLOOR_SHOW",
    GET_YANCHU_LIST:"GET_YANCHU_LIST",
    GET_YANCHU_NAV:"GET_YANCHU_NAV",
    UPGETTOURRECOMMENDLIST:"UPGETTOURRECOMMENDLIST",//巡回演出
    GET_CAROUSEL_LIST:"GET_CAROUSEL_LIST",
    GET_NAV_LIST:"GET_NAV_LIST",
    UPABOUTRECOMMEND:"UPABOUTRECOMMEND",
}